### ISSUE TITLE
Asp.Net core?

### ISSUE THREAD

**Issue by gbjbaanb** [anthonychu/aspnet-core-csp#1]
Looking at the using references, its not Core at all, but plain old asp.net

Adding the files to a asp.net core project failes to compile, even after updating the usings.

**Comment by anthonychu** [comment]
This was ASP.NET Core before it was released, and before they switched over to use a `.csproj` file again. It ran on both .NET Framework and .NET Core. I haven't tried but I think you can take the relevant parts and put it in an ASP.NET Core 2 or 3 project and they should run fine. The simple CSP solution presented here is a small middleware that adds headers and a reporting endpoint in a controller.

Some of the usings might have changed. I'll take a quick look at porting it to ASP.NET Core 2.

**Comment by gbjbaanb** [comment]
Hi Anthony, thanks for replying. I tried the code with asp.ner core 2.0, and it fails to compile. Thingsa change way too much in the asp.net core world! No doubt it'll all break in net core 3.0 as well :-)

The main issue was getting the content type handler added to the MvcOptions.

I tried this, but it still didn't work. If you have any ideas, let me know, [nobody on SO](https://stackoverflow.com/questions/57146684/csp-report-endpoint-in-asp-net-core?noredirect=1#comment100903586_57146684) knows either.

```
    services.Configure<MvcOptions>(options => {
        options.InputFormatters.OfType<JsonInputFormatter>().First().SupportedMediaTypes.Add(
            new MediaTypeHeaderValue("application/csp-report")
        );
    });

```

**Comment by gbjbaanb** [comment]
Kirk Larkin found the problem and [answered it on SO](https://stackoverflow.com/a/57223057/13744). There are 2 objects of type JsonInputFormatter in the MVC options, I just had the wrong one. Your code pretty much all works but for adding the content-type handler into those options, that's changed since version you wrote.

```
services.Configure<MvcOptions>(options => {
    options.InputFormatters.OfType<JsonInputFormatter>().Last().SupportedMediaTypes.Add(
        new MediaTypeHeaderValue("application/csp-report"));
});
```
